# Local WordPress environment
#
# This configuration is intended for the development environment only!
#
# Images:
#   - db: https://hub.docker.com/_/mysql/ or https://hub.docker.com/_/mariadb
#   - wordpress: https://hub.docker.com/_/wordpress/
#   - phpmyadmin: https://hub.docker.com/_/phpmyadmin
#
# WP-CLI:
# docker compose run --rm wp-cli wp config list
# https://developer.wordpress.org/cli/commands/
#
# Docker:
# https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
#
# Compose:
# https://docs.docker.com/compose/compose-file/
# https://github.com/docker/awesome-compose/blob/master/official-documentation-samples/wordpress/README.md
#
# XDebug:
# https://github.com/wpdiaries/wordpress-xdebug
# https://www.wpdiaries.com/wordpress-with-xdebug-for-docker/#using-multiple-docker-compose-files
# Set the XDEBUG_CONFIG as described here: https://xdebug.org/docs/remote
#
# Examples:
# https://github.com/kassambara/wordpress-docker-compose/blob/master/docker-compose-onlinehost.yml
# https://www.digitalocean.com/community/tutorials/how-to-install-wordpress-with-docker-compose
# https://github.com/nezhar/wordpress-docker-compose/blob/master/docker-compose.yml

services:
  db:
    image: mysql:${MYSQL_VERSION:-8.4.1}
    container_name: ${COMPOSE_PROJECT_NAME}_db
    restart: unless-stopped
    command: [
      '--max_allowed-packet=128M',
      '--mysql-native-password=ON',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    environment:
      MYSQL_DATABASE: ${COMPOSE_PROJECT_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - wordpress_default_network

  wordpress:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile # You need it only if you want to use some custom name for your Dockerfile
      context: ./ # A path to a directory containing a Dockerfile, or a URL to a git repository
      args:
        - WORDPRESS_VERSION=${WORDPRESS_VERSION}
        - XDEBUG_BRANCH=${XDEBUG_BRANCH}
    user: "root" # Use "www-data" in the production environment.
    container_name: ${COMPOSE_PROJECT_NAME}_wordpress_xdebug
    restart: unless-stopped
    ports:
      - ${WORDPRESS_PORT:-8000}:80
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST:-db}
      WORDPRESS_DB_NAME: ${COMPOSE_PROJECT_NAME}
      WORDPRESS_DB_USER: ${DATABASE_USER}
      WORDPRESS_DB_PASSWORD: ${DATABASE_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX:-wp_}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG:-1}
      XDEBUG_CONFIG: client_host=172.17.0.1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_MEMORY_LIMIT', '512M' );
        define( 'WP_DEBUG_LOG', 'wp-content/debug.log' );
        define( 'WP_ENVIRONMENT_TYPE', 'local' );
    volumes:
      - ../conf/php/conf.d/php-tweaks.ini:/usr/local/etc/php/conf.d/php-tweaks.ini
      - ../conf/apache2/conf-available/security.conf:/etc/apache2/conf-available/security.conf
      - ../wordpress:/var/www/html
    networks:
      - wordpress_default_network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:${PHPMYADMIN_VERSION:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
    restart: unless-stopped
    ports:
      - ${PHPMYADMIN_PORT:-8001}:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MAX_EXECUTION_TIME: 1200
      MEMORY_LIMIT: 4G
      UPLOAD_LIMIT: 1G
    networks:
      - wordpress_default_network

  # TODO Improve wp-cli
  wp_cli:
    depends_on:
      - db
      - wordpress
    volumes_from:
      - wordpress
    image: wordpress:cli
    container_name: ${COMPOSE_PROJECT_NAME}_wp_cli
    user: "33:33"  # This is the UID:GID for www-data
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST:-db}
      WORDPRESS_DB_NAME: ${COMPOSE_PROJECT_NAME}
      WORDPRESS_DB_USER: ${DATABASE_USER}
      WORDPRESS_DB_PASSWORD: ${DATABASE_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX:-wp_}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG:-1}
      WP_CLI_CACHE_DIR: /var/www/html/.wp-cli/cache/
    volumes:
      - ../conf/php/conf.d/php-tweaks.ini:/usr/local/etc/php/conf.d/php-tweaks.ini
      - ../wordpress:/var/www/html
    working_dir: /var/www/html
    networks:
      - wordpress_default_network

volumes:
  db_data:
    name: ${COMPOSE_PROJECT_NAME}_db_data

networks:
  wordpress_default_network:
    name: ${COMPOSE_PROJECT_NAME}_default_network
